weights: activelearning/yolov5s.pt
cfg: models/yolo_gun.yaml
data: data/gun.yaml
hyp: data/hyp.scratch.yaml
epochs: 2
batch_size: 1
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: 0
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
name: gun
exist_ok: 1
total_batch_size: 1
world_size: 1
global_rank: -1
save_dir: runs/train/gun
